/**
 * Generates src/data/outfits.json (explicit estate x sex x stage x outfit -> look table).
 * Edit the rules here (or edit the JSON by hand; this script overwrites it).
 * Usage: npx tsx tools/lpc/gen-outfits.ts
 *
 * Layer ids are LPC generator sheet_definition names (or our generated child_* layers).
 * Medieval choices: serfs undyed wool/linen hoods; freemen/artisans better cloth, aprons;
 * merchants buttoned wool + caps; clergy long habits, cowls/wimples, cross;
 * knights mail + tabard for war, capes for court; nobles rich dyes, capes, circlets.
 * Where a choice exists, CC0 / CC-BY / OGA-BY layers are preferred (e.g. longsleeve2 family is OGA-BY only).
 */
import { writeFileSync } from 'node:fs';
import type { Estate, LookSlot, OutfitKind, OutfitsData, Sex, Stage } from '../../src/render/lpc/types';

type Slot = LookSlot & { hides?: string[]; optional?: boolean };
const S = (slot: string, pick: string[], dye?: string[], extra: Partial<Slot> = {}): Slot => ({ slot, pick, ...(dye ? { dye } : {}), ...extra });

const ESTATES: Estate[] = ['serf', 'freeman', 'artisan', 'merchant', 'clergy', 'knight', 'noble'];
const SEXES: Sex[] = ['male', 'female'];
const STAGES: Stage[] = ['child', 'teen', 'adult', 'elder'];
const OUTFITS: OutfitKind[] = ['everyday', 'work', 'formal', 'sleep', 'winter', 'bath'];

// ---------------------------------------------------------------- common pieces
const SHIRT_PLAIN = ['torso_clothes_longsleeve2', 'torso_clothes_longsleeve'];
const SHIRT_FINE = ['torso_clothes_longsleeve2_buttoned', 'torso_clothes_longsleeve2_vneck', 'torso_clothes_longsleeve_scoop'];
const SHIRT_LADY = ['torso_clothes_longsleeve2_scoop', 'torso_clothes_longsleeve_scoop'];
const SHIRT_WORK = ['torso_clothes_shortsleeve', 'torso_clothes_sleeveless2'];
const HOSE = ['legs_hose', 'legs_pants2'];
const TROUSERS = ['legs_pants', 'legs_pants2'];
const LONG_SKIRT = ['legs_skirts_plain'];
const SHOES_POOR = ['feet_shoes_basic', 'feet_shoes_revised'];
const SHOES_GOOD = ['feet_shoes_ghillies', 'feet_boots_basic'];
const BOOTS_FINE = ['feet_boots_rim', 'feet_boots_fold'];
const HOOD = (chance: number) => S('hat', ['hat_hood_sack_cloth', 'hat_hood_cloth'], ['main'], { chance, hides: ['hair'] });
const WIMPLE = (chance: number) => S('hat', ['hat_hood_hijab'], ['fixed:white'], { chance, hides: ['hair'] });
const KERCHIEF = (chance: number) => S('hat', ['hat_headband_kerchief'], ['accent'], { chance });
const MANTLE = S('cloak', ['shoulders_mantal'], ['accent']);
const CAPE = (chance = 1) => S('cloak', ['cape_solid'], ['main'], { chance, optional: true });
const CAPE_TRIM = (chance = 1) => S('cloaktrim', ['cape_trim'], ['trim'], { chance, optional: true });
const NIGHTGOWN = [S('torso', ['torso_clothes_longsleeve'], ['fixed:white']), S('legs', LONG_SKIRT, ['fixed:white'])];
const BATH_M = [S('legs', ['legs_shorts'], ['fixed:white'])];
const BATH_F = [S('torso', ['torso_clothes_sleeveless2', 'torso_clothes_sleeveless_tanktop'], ['fixed:white']), S('legs', ['legs_shorts'], ['fixed:white'])];

// children: synthetic garments generated by tools/lpc/gen-child-garments.ts (LPC has walk-only child clothes)
const CHILD_M = (shoes: number) => [S('torso', ['child_tunic'], ['main']), S('legs', ['child_hose'], ['accent']), S('feet', ['child_shoes'], ['fixed:leather'], { chance: shoes })];
const CHILD_F = (shoes: number) => [S('torso', ['child_dress'], ['main']), S('feet', ['child_shoes'], ['fixed:leather'], { chance: shoes })];
const CHILD_SLEEP = [S('torso', ['child_dress'], ['fixed:white'])];
const CHILD_BATH = [S('legs', ['child_hose'], ['fixed:white'])];
const CHILD_WINTER_M = [S('torso', ['child_tunic_long'], ['main']), S('legs', ['child_hose'], ['accent']), S('feet', ['child_shoes'], ['fixed:leather'])];
const CHILD_WINTER_F = [S('torso', ['child_dress_long'], ['main']), S('feet', ['child_shoes'], ['fixed:leather'])];

// ---------------------------------------------------------------- adult looks per estate
type Looks = Record<OutfitKind, Slot[]>;
const adult: Record<Estate, Record<Sex, Looks>> = {
  serf: {
    male: {
      everyday: [S('torso', SHIRT_PLAIN, ['main']), S('legs', HOSE, ['accent']), S('feet', SHOES_POOR, ['fixed:leather'], { chance: 0.6 }), HOOD(0.35)],
      work: [S('torso', SHIRT_WORK, ['main']), S('legs', HOSE, ['accent']), S('feet', SHOES_POOR, ['fixed:leather'], { chance: 0.5 }), HOOD(0.25)],
      formal: [S('torso', SHIRT_PLAIN, ['main']), S('legs', TROUSERS, ['accent']), S('feet', SHOES_POOR, ['fixed:leather'])],
      sleep: NIGHTGOWN,
      winter: [S('torso', SHIRT_PLAIN, ['main']), S('legs', TROUSERS, ['accent']), S('feet', ['feet_boots_basic'], ['fixed:leather']), MANTLE, HOOD(1)],
      bath: BATH_M,
    },
    female: {
      everyday: [S('torso', ['torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', SHOES_POOR, ['fixed:leather'], { chance: 0.6 }), KERCHIEF(0.5)],
      work: [S('torso', ['torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['accent']), S('over', ['torso_aprons_apron'], ['fixed:white']), KERCHIEF(0.7)],
      formal: [S('torso', ['torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', SHOES_POOR, ['fixed:leather']), WIMPLE(0.6)],
      sleep: NIGHTGOWN,
      winter: [S('torso', ['torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', ['feet_boots_basic'], ['fixed:leather']), MANTLE, HOOD(1)],
      bath: BATH_F,
    },
  },
  freeman: {
    male: {
      everyday: [S('torso', SHIRT_PLAIN, ['main']), S('legs', TROUSERS, ['accent']), S('feet', SHOES_POOR, ['fixed:leather']), S('hat', ['hat_headband_tied'], ['trim'], { chance: 0.2 })],
      work: [S('torso', SHIRT_WORK, ['main']), S('legs', TROUSERS, ['accent']), S('feet', ['feet_boots_basic'], ['fixed:leather']), HOOD(0.2)],
      formal: [S('torso', SHIRT_FINE, ['main']), S('legs', TROUSERS, ['accent']), S('feet', SHOES_GOOD, ['fixed:leather'])],
      sleep: NIGHTGOWN,
      winter: [S('torso', SHIRT_PLAIN, ['main']), S('legs', TROUSERS, ['accent']), S('feet', ['feet_boots_fold'], ['fixed:leather']), MANTLE, HOOD(0.8)],
      bath: BATH_M,
    },
    female: {
      everyday: [S('torso', ['torso_clothes_longsleeve', 'torso_clothes_longsleeve2', 'torso_clothes_shortsleeve'], ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', SHOES_POOR, ['fixed:leather']), KERCHIEF(0.4)],
      work: [S('torso', ['torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['accent']), S('over', ['torso_aprons_apron'], ['fixed:white']), KERCHIEF(0.6)],
      formal: [S('torso', SHIRT_LADY, ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', SHOES_GOOD, ['fixed:leather']), WIMPLE(0.5)],
      sleep: NIGHTGOWN,
      winter: [S('torso', ['torso_clothes_longsleeve2', 'torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', ['feet_boots_fold'], ['fixed:leather']), MANTLE, HOOD(0.9)],
      bath: BATH_F,
    },
  },
  artisan: {
    male: {
      everyday: [S('torso', SHIRT_PLAIN, ['main']), S('legs', TROUSERS, ['accent']), S('feet', SHOES_GOOD, ['fixed:leather']), S('hat', ['hat_cap_leather'], ['fixed:leather'], { chance: 0.3 })],
      work: [S('torso', SHIRT_WORK, ['main']), S('legs', TROUSERS, ['accent']), S('over', ['torso_aprons_apron'], ['fixed:leather']), S('feet', ['feet_boots_basic'], ['fixed:leather'])],
      formal: [S('torso', SHIRT_FINE, ['main']), S('legs', ['legs_formal', 'legs_pants'], ['accent']), S('feet', SHOES_GOOD, ['fixed:leather'])],
      sleep: NIGHTGOWN,
      winter: [S('torso', SHIRT_PLAIN, ['main']), S('legs', TROUSERS, ['accent']), S('feet', ['feet_boots_fold'], ['fixed:leather']), MANTLE, HOOD(0.6)],
      bath: BATH_M,
    },
    female: {
      everyday: [S('torso', ['torso_clothes_longsleeve2', 'torso_clothes_longsleeve2_vneck', 'torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', SHOES_GOOD, ['fixed:leather']), KERCHIEF(0.4)],
      work: [S('torso', ['torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['accent']), S('over', ['torso_aprons_apron'], ['fixed:white']), KERCHIEF(0.8)],
      formal: [S('torso', SHIRT_LADY, ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', SHOES_GOOD, ['fixed:leather']), WIMPLE(0.4)],
      sleep: NIGHTGOWN,
      winter: [S('torso', ['torso_clothes_longsleeve2', 'torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', ['feet_boots_fold'], ['fixed:leather']), MANTLE, HOOD(0.8)],
      bath: BATH_F,
    },
  },
  merchant: {
    male: {
      everyday: [S('torso', SHIRT_FINE, ['main']), S('legs', ['legs_formal', 'legs_pants'], ['accent']), S('feet', SHOES_GOOD, ['fixed:leather']), S('hat', ['hat_cap_bonnie'], ['accent'], { chance: 0.6 })],
      work: [S('torso', SHIRT_PLAIN, ['main']), S('legs', TROUSERS, ['accent']), S('feet', SHOES_GOOD, ['fixed:leather']), S('hat', ['hat_cap_bonnie'], ['accent'], { chance: 0.4 })],
      formal: [S('torso', ['torso_clothes_longsleeve2_buttoned'], ['main']), S('legs', ['legs_formal'], ['accent']), S('feet', BOOTS_FINE, ['fixed:black']), S('neck', ['neck_necklace_chain'], ['fixed:gold'], { chance: 0.5, optional: true }), S('hat', ['hat_cap_bonnie'], ['accent'], { chance: 0.6 })],
      sleep: NIGHTGOWN,
      winter: [S('torso', SHIRT_FINE, ['main']), S('legs', ['legs_formal'], ['accent']), S('feet', BOOTS_FINE, ['fixed:leather']), S('cloak', ['shoulders_mantal'], ['trim']), S('hat', ['hat_cap_bonnie'], ['accent'])],
      bath: BATH_M,
    },
    female: {
      everyday: [S('torso', SHIRT_LADY, ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', SHOES_GOOD, ['fixed:leather']), KERCHIEF(0.3)],
      work: [S('torso', ['torso_clothes_longsleeve2', 'torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', SHOES_GOOD, ['fixed:leather']), KERCHIEF(0.5)],
      formal: [S('torso', SHIRT_LADY, ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', SHOES_GOOD, ['fixed:black']), S('neck', ['neck_necklace_chain'], ['fixed:gold'], { optional: true }), WIMPLE(0.4)],
      sleep: NIGHTGOWN,
      winter: [S('torso', SHIRT_LADY, ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', BOOTS_FINE, ['fixed:leather']), S('cloak', ['shoulders_mantal'], ['trim']), HOOD(0.6)],
      bath: BATH_F,
    },
  },
  clergy: {
    male: {
      everyday: [S('torso', ['torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['main']), S('feet', ['feet_sandals'], ['fixed:leather']), S('neck', ['neck_amulet_cross'], ['fixed:iron_red'], { optional: true }), HOOD(0.4)],
      work: [S('torso', ['torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['main']), S('feet', ['feet_sandals'], ['fixed:leather']), HOOD(0.3)],
      formal: [S('torso', ['torso_clothes_longsleeve'], ['fixed:white']), S('legs', LONG_SKIRT, ['fixed:white']), S('feet', ['feet_slippers'], ['fixed:white']), S('cloak', ['shoulders_mantal'], ['trim']), S('neck', ['neck_amulet_cross'], ['fixed:gold_red'], { optional: true })],
      sleep: NIGHTGOWN,
      winter: [S('torso', ['torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['main']), S('feet', ['feet_boots_basic'], ['fixed:leather']), MANTLE, HOOD(1)],
      bath: BATH_M,
    },
    female: {
      everyday: [S('torso', ['torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['main']), S('feet', ['feet_shoes_basic'], ['fixed:black']), WIMPLE(1), S('neck', ['neck_amulet_cross'], ['fixed:iron_red'], { optional: true })],
      work: [S('torso', ['torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['main']), S('over', ['torso_aprons_apron'], ['fixed:white']), WIMPLE(1)],
      formal: [S('torso', ['torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['main']), S('feet', ['feet_shoes_basic'], ['fixed:black']), WIMPLE(1), S('cloak', ['shoulders_mantal'], ['fixed:white']), S('neck', ['neck_amulet_cross'], ['fixed:gold_red'], { optional: true })],
      sleep: NIGHTGOWN,
      winter: [S('torso', ['torso_clothes_longsleeve'], ['main']), S('legs', LONG_SKIRT, ['main']), S('feet', ['feet_boots_basic'], ['fixed:black']), MANTLE, WIMPLE(1)],
      bath: BATH_F,
    },
  },
  knight: {
    male: {
      everyday: [S('torso', SHIRT_FINE, ['main']), S('legs', ['legs_pants', 'legs_formal'], ['accent']), S('feet', BOOTS_FINE, ['fixed:leather']), S('waist', ['belt_obi'], ['trim'], { chance: 0 })],
      work: [S('torso', ['torso_chainmail'], ['metal']), S('over', ['torso_jacket_tabard'], ['main']), S('legs', ['legs_armour'], ['metal']), S('feet', ['feet_armour'], ['metal']), S('arms', ['arms_gloves'], ['metal']), S('hat', ['hat_helmet_nasal', 'hat_helmet_mail', 'hat_helmet_bascinet'], ['metal'], { hides: ['hair'] })],
      formal: [S('torso', SHIRT_FINE, ['main']), S('legs', ['legs_formal'], ['accent']), S('feet', BOOTS_FINE, ['fixed:black']), CAPE(), CAPE_TRIM(0.6), S('neck', ['neck_capeclip'], ['trim', 'fixed:gold'], { optional: true })],
      sleep: NIGHTGOWN,
      winter: [S('torso', SHIRT_FINE, ['main']), S('legs', ['legs_formal'], ['accent']), S('feet', BOOTS_FINE, ['fixed:leather']), CAPE(), S('cloak2', ['shoulders_mantal'], ['trim']), HOOD(0.5)],
      bath: BATH_M,
    },
    female: {
      everyday: [S('torso', SHIRT_LADY, ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', SHOES_GOOD, ['fixed:leather']), S('neck', ['neck_necklace_chain'], ['fixed:silver'], { chance: 0.5, optional: true })],
      work: [S('torso', ['torso_chainmail'], ['metal']), S('over', ['torso_jacket_tabard'], ['main']), S('legs', ['legs_armour'], ['metal']), S('feet', ['feet_armour'], ['metal']), S('arms', ['arms_gloves'], ['metal']), S('hat', ['hat_helmet_mail'], ['metal'], { hides: ['hair'] })],
      formal: [S('torso', SHIRT_LADY, ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', SHOES_GOOD, ['fixed:black']), CAPE(), CAPE_TRIM(0.6), S('neck', ['neck_necklace_chain'], ['fixed:silver'], { optional: true })],
      sleep: NIGHTGOWN,
      winter: [S('torso', SHIRT_LADY, ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', BOOTS_FINE, ['fixed:leather']), CAPE(), S('cloak2', ['shoulders_mantal'], ['trim']), HOOD(0.5)],
      bath: BATH_F,
    },
  },
  noble: {
    male: {
      everyday: [S('torso', SHIRT_FINE, ['main']), S('legs', ['legs_formal', 'legs_hose'], ['accent']), S('feet', BOOTS_FINE, ['fixed:black']), S('cloak', ['shoulders_mantal'], ['trim'], { chance: 0.4 }), S('neck', ['neck_necklace_chain'], ['fixed:gold'], { chance: 0.5, optional: true })],
      work: [S('torso', SHIRT_FINE, ['main']), S('legs', ['legs_formal'], ['accent']), S('feet', BOOTS_FINE, ['fixed:black'])],
      formal: [S('torso', ['torso_clothes_longsleeve2_buttoned'], ['main']), S('legs', ['legs_formal'], ['accent']), S('feet', BOOTS_FINE, ['fixed:black']), CAPE(), CAPE_TRIM(), S('neck', ['neck_capeclip'], ['trim', 'fixed:gold'], { optional: true }), S('hat', ['hat_formal_crown'], ['fixed:crown_gold'], { chance: 0.3 })],
      sleep: NIGHTGOWN,
      winter: [S('torso', SHIRT_FINE, ['main']), S('legs', ['legs_formal'], ['accent']), S('feet', BOOTS_FINE, ['fixed:black']), CAPE(), CAPE_TRIM(), S('cloak2', ['shoulders_mantal'], ['fixed:white'])],
      bath: BATH_M,
    },
    female: {
      everyday: [S('torso', SHIRT_LADY, ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', SHOES_GOOD, ['fixed:black']), S('neck', ['neck_necklace_chain'], ['fixed:gold'], { chance: 0.7, optional: true }), S('hat', ['hat_formal_tiara'], ['fixed:tiara_gold'], { chance: 0.3 })],
      work: [S('torso', SHIRT_LADY, ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', SHOES_GOOD, ['fixed:black'])],
      formal: [S('torso', SHIRT_LADY, ['main']), S('legs', LONG_SKIRT, ['main']), S('feet', SHOES_GOOD, ['fixed:black']), CAPE(), CAPE_TRIM(), S('neck', ['neck_necklace_chain'], ['fixed:gold'], { optional: true }), S('hat', ['hat_formal_tiara'], ['fixed:tiara_gold'])],
      sleep: NIGHTGOWN,
      winter: [S('torso', SHIRT_LADY, ['main']), S('legs', LONG_SKIRT, ['accent']), S('feet', BOOTS_FINE, ['fixed:black']), CAPE(), CAPE_TRIM(), S('cloak2', ['shoulders_mantal'], ['fixed:white'])],
      bath: BATH_F,
    },
  },
};

const childShoes: Record<Estate, number> = { serf: 0.2, freeman: 0.6, artisan: 0.8, merchant: 1, clergy: 0.8, knight: 1, noble: 1 };
function childLooks(e: Estate, sex: Sex): Looks {
  const base = sex === 'male' ? CHILD_M(childShoes[e]) : CHILD_F(childShoes[e]);
  return {
    everyday: base,
    work: base,
    formal: sex === 'male' ? CHILD_M(1) : CHILD_F(1),
    sleep: CHILD_SLEEP,
    winter: sex === 'male' ? CHILD_WINTER_M : CHILD_WINTER_F,
    bath: CHILD_BATH,
  };
}

// ---------------------------------------------------------------- dyes (GDD 16-2 sumptuary table, cumulative)
const D_ALL = ['white', 'tan', 'brown', 'walnut', 'leather', 'gray', 'charcoal'];
const D_FREE = [...D_ALL, 'blue', 'bluegray', 'sky', 'green', 'forest', 'yellow'];
const D_ART = [...D_FREE, 'red', 'rose', 'orange'];
const D_MER = [...D_ART, 'navy', 'teal', 'slate', 'black'];
const D_KNI = [...D_MER]; // + heraldic tinctures (all of the above); crimson & purple stay noble-only
const D_NOB = [...D_KNI, 'maroon', 'purple', 'lavender', 'pink'];
const D_CLE = ['black', 'white', 'brown', 'gray', 'charcoal', 'tan'];

const dyes: OutfitsData['dyes'] = {
  serf: { main: ['brown', 'tan', 'gray', 'walnut', 'white', 'leather'], accent: ['brown', 'gray', 'walnut', 'charcoal', 'tan'], trim: D_ALL },
  freeman: { main: ['blue', 'green', 'bluegray', 'forest', 'brown', 'tan', 'gray', 'yellow'], accent: ['brown', 'walnut', 'gray', 'charcoal', 'forest', 'bluegray'], trim: D_FREE },
  artisan: { main: ['red', 'blue', 'green', 'rose', 'orange', 'forest', 'brown', 'bluegray'], accent: ['brown', 'walnut', 'charcoal', 'gray', 'tan', 'leather'], trim: D_ART },
  merchant: { main: ['navy', 'teal', 'red', 'black', 'forest', 'blue', 'slate'], accent: ['black', 'charcoal', 'navy', 'walnut', 'brown', 'slate'], trim: D_MER },
  clergy: { main: ['black', 'brown', 'gray', 'white', 'charcoal'], accent: D_CLE, trim: ['white', 'black', 'red'] },
  knight: { main: ['red', 'blue', 'navy', 'green', 'black', 'yellow', 'white', 'forest'], accent: ['black', 'charcoal', 'navy', 'walnut', 'slate', 'gray'], trim: D_KNI },
  noble: { main: ['maroon', 'purple', 'navy', 'red', 'forest', 'black', 'lavender', 'teal'], accent: ['black', 'charcoal', 'navy', 'maroon', 'white', 'slate'], trim: D_NOB },
};

// ---------------------------------------------------------------- assemble
const looks: Record<string, Slot[]> = {};
const byContent = new Map<string, string>();
const estates = {} as OutfitsData['estates'];
for (const e of ESTATES) {
  estates[e] = {} as OutfitsData['estates'][Estate];
  for (const sex of SEXES) {
    estates[e][sex] = {} as Record<Stage, Record<OutfitKind, string>>;
    for (const st of STAGES) {
      const set = st === 'child' ? childLooks(e, sex) : adult[e][sex];
      const key = st === 'child' ? 'child' : 'adult';
      estates[e][sex][st] = {} as Record<OutfitKind, string>;
      for (const o of OUTFITS) {
        const json = JSON.stringify(set[o]);
        let id = byContent.get(json);
        if (!id) {
          id = `${e}.${sex}.${key}.${o}`;
          looks[id] = set[o];
          byContent.set(json, id);
        }
        estates[e][sex][st][o] = id;
      }
    }
  }
}

const data: OutfitsData & { _comment: string } = {
  _comment: 'Generated by tools/lpc/gen-outfits.ts. Layer ids = LPC generator sheet_definitions names (child_* = tools/lpc/gen-child-garments.ts). dye roles: main/accent/trim pick from dyes[estate]; fixed:<name> is a fixed colour or variant; metal picks from metals[estate]. hides: slots removed when worn. optional: layer is skipped in animations it lacks instead of changing the animation source.',
  skins: ['lpcr.porcelain', 'lpcr.ivory', 'light', 'lpcr.peach', 'amber', 'lpcr.tan', 'olive', 'lpcr.honey', 'taupe', 'bronze', 'brown', 'lpcr.coffee'],
  eyes: ['brown', 'blue', 'green', 'gray'],
  hair: {
    colors: ['raven', 'black', 'dark_brown', 'chestnut', 'light_brown', 'sandy', 'blonde', 'strawberry', 'ginger', 'redhead'],
    elderColors: ['gray', 'white', 'platinum', 'ash'],
    styles: {
      male: {
        child: ['parted_side_bangs', 'swoop_side', 'relm_short', 'topknot_short'],
        teen: ['plain', 'parted', 'page', 'bedhead', 'messy1', 'mop', 'bangsshort', 'curly_short'],
        adult: ['plain', 'parted', 'page', 'page2', 'bedhead', 'messy1', 'unkempt', 'buzzcut', 'curly_short', 'long_messy'],
        elder: ['balding', 'buzzcut', 'plain', 'page', 'unkempt', 'long_messy'],
      },
      female: {
        child: ['wavy_child', 'parted_side_bangs2', 'relm_short', 'topknot_short2'],
        teen: ['long', 'long_straight', 'braid', 'ponytail', 'pigtails_bangs', 'loose', 'wavy', 'half_up'],
        adult: ['long', 'long_straight', 'braid', 'braid2', 'ponytail', 'bangs_bun', 'long_tied', 'princess', 'loose', 'wavy', 'half_up', 'shoulderl'],
        elder: ['bangs_bun', 'long_tied', 'braid', 'loose', 'half_up'],
      },
    },
    beards: ['beards_beard', 'beards_medium', 'beards_trimmed', 'beards_5oclock_shadow', 'beards_mustache'],
    beardChance: { child: 0, teen: 0, adult: 0.45, elder: 0.7 },
  },
  heads: {
    male: {
      child: ['heads_human_child'],
      teen: ['heads_human_male_small'],
      adult: ['heads_human_male', 'heads_human_male', 'heads_human_male_plump', 'heads_human_male_gaunt'],
      elder: ['heads_human_male_elderly'],
    },
    female: {
      child: ['heads_human_child'],
      teen: ['heads_human_female_small'],
      adult: ['heads_human_female'],
      elder: ['heads_human_female_elderly'],
    },
  },
  stageExtras: { child: [], teen: [], adult: [], elder: ['head_wrinkles'] },
  dyes,
  metals: {
    serf: ['iron'], freeman: ['iron'], artisan: ['iron', 'steel'], merchant: ['iron', 'steel'],
    clergy: ['iron'], knight: ['steel', 'iron'], noble: ['steel', 'silver'],
  },
  looks,
  estates,
};

writeFileSync('src/data/outfits.json', JSON.stringify(data, null, 1) + '\n');
console.log(`wrote src/data/outfits.json: ${Object.keys(looks).length} looks`);
