// 건축 모드: 놓인 가구 고르기 → 색 바꾸기 · 돌리기 · 팔기, 벽 고르기 → 칠하기 (실제 클릭)
import { chromium } from 'playwright';
const browser = await chromium.launch({ channel: 'msedge' });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
const errs = [];
page.on('pageerror', (e) => errs.push(e.message));
page.on('console', (m) => m.type() === 'error' && errs.push(m.text()));
await page.goto('http://127.0.0.1:5188/?town=ashford&new=0');
await page.waitForFunction(() => window.__game?.ready?.(), null, { timeout: 120_000 });
await page.waitForTimeout(1500);
await page.keyboard.press('b');
await page.waitForTimeout(800);
const at = (defId) => page.evaluate((id) => { const hk = window.__hk; const L = hk.town.def.lots.find((l) => l.id === hk.client.snap.town.playerLot).rect; const H = hk.lotRows(); const o = hk.client.snap.objects.find((q) => q.defId === id && q.x >= L[0] && q.x <= L[2] && (q.y % H) >= L[1] && (q.y % H) <= L[3]); const n = o && hk.world.objs.get(o.uid); if (!n) return null; const r = n.node.ref; return hk.renderer.worldToScreen(n.node.left - r.anchorX + r.w / 2, n.node.bottom - r.anchorY + r.h * 0.55); }, defId);
const obj = (id) => page.evaluate((d) => { const hk = window.__hk; const L = hk.town.def.lots.find((l) => l.id === hk.client.snap.town.playerLot).rect; const H = hk.lotRows(); return hk.client.snap.objects.find((q) => q.defId === d && q.x >= L[0] && q.x <= L[2] && (q.y % H) >= L[1] && (q.y % H) <= L[3]); }, id);
const out = {};
await page.click('.sub-tab[data-sub="obj"]');
await page.waitForTimeout(300);
const p = await at('bench_bedfoot');
console.log('p', JSON.stringify(p));
await page.mouse.click(p.x, p.y);
await page.waitForTimeout(500);
out.selected = await page.evaluate(() => ({ name: document.querySelector('.dock-detail.placed .det-name')?.textContent, vars: document.querySelectorAll('.sel-var .variant').length, acts: [...document.querySelectorAll('.sel-act')].map((b) => b.dataset.act), lit: window.__hk.world.many.length }));
await page.screenshot({ path: 'artifacts/qa/play/build_sel_obj.png' });
await page.click('.sel-var .variant[data-variant="walnut"]');
await page.waitForTimeout(700);
out.recolor = (await obj('bench_bedfoot'))?.variant;
const rot0 = (await obj('bench_bedfoot'))?.rot ?? 0;
await page.click('.sel-act[data-act="rotate"]');
await page.waitForTimeout(700);
out.rotated = ((await obj('bench_bedfoot'))?.rot ?? 0) !== rot0;
await page.click('.sel-act[data-act="sell"]');
await page.waitForTimeout(700);
out.sold = !(await obj('bench_bedfoot'));
// 벽: 짓기 탭 → 옮기기(손) 도구 → 벽 칸 누르기
await page.click('.sub-tab[data-sub="make"]');
await page.click('.tool-btn[data-tool="hand"]');
await page.waitForTimeout(300);
const wall = await page.evaluate(() => { const hk = window.__hk; const lot = hk.world.currentLot; const L = hk.town.def.lots.find((l) => l.id === hk.client.snap.town.playerLot).rect; for (let y = L[1]; y <= L[3]; y++) for (let x = L[0]; x <= L[2]; x++) { const s = lot.walls[y * lot.w + x]; if (s && !s.startsWith('fence')) { const q = hk.world.project(x + 0.5, y + 0.5); return { x, y, s, sp: hk.renderer.worldToScreen(q.x, q.y - 8) }; } } return null; });
await page.mouse.click(wall.sp.x, wall.sp.y);
await page.waitForTimeout(500);
out.wallSel = await page.evaluate(() => ({ name: document.querySelector('.dock-detail.placed .det-name')?.textContent, styles: document.querySelectorAll('.sel-wall').length }));
await page.screenshot({ path: 'artifacts/qa/play/build_sel_wall.png' });
const target = await page.evaluate((cur) => [...document.querySelectorAll('.sel-wall:not(:disabled)')].map((b) => b.dataset.style).find((s) => s !== cur), wall.s);
await page.click(`.sel-wall[data-style="${target}"]`);
await page.waitForTimeout(800);
out.painted = await page.evaluate((w) => { const lot = window.__hk.world.currentLot; return lot.walls[w.y * lot.w + w.x]; }, wall);
out.target = target;
await page.screenshot({ path: 'artifacts/qa/play/build_sel_wall2.png' });
console.log(JSON.stringify({ out, errs }));
await browser.close();
